apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: couchdb-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.nutanix-volume
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
# Hinweis: 'no-provisioner' bedeutet, dass PVs manuell erstellt werden m√ºssen.